<a href="https://colab.research.google.com/github/ivanovyeppez/talento-tech/blob/main/Entrenamiento/Diccionarios_Pandas_Ciclos_Funciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 IA Innovador — Clase práctica
**Tema:** Estructuras de datos (énfasis en diccionarios) ➜ Tablas con Pandas ➜ Ciclos ➜ Funciones ➜ Laboratorio final  
**Duración total:** 3 horas  
**Formato:** Google Colab  
**Fecha de preparación:** 2025-08-14

---

## Objetivos
- Comprender y manipular **diccionarios** en Python.
- Crear **tablas** a partir de listas de diccionarios usando **pandas**.
- Recorrer datos con **ciclos** (`for`, `while`).
- Crear y usar **funciones**.
- Integrar todo en un **laboratorio final**.

By **Ing. Engler Gonzalez **
> 💡 Sugerencia: ejecuta celda por celda y lee las instrucciones antes de correr el código.

## 0) Configuración rápida

In [ ]:
import pandas as pd

## 1) Diccionarios (45 min)
Un **diccionario** almacena pares **clave → valor**.

### Ejemplo guiado

In [ ]:
# Ejemplo: crear y leer un diccionario
estudiante = {
    "nombre": "Ana",
    "edad": 20,
    "curso": "Python"
}

# Imprime un valor por su clave
print(estudiante["nombre"])  # Esperado: Ana

Ana

### Operaciones básicas
- Agregar/modificar elementos
- Eliminar elementos
- Recorrer el diccionario

In [ ]:
# 👉 Completa las líneas marcadas con TODO
persona = {"nombre": "Luis", "edad": 22}

# Agrega una clave "ciudad" con el valor "Pasto"
# TODO: persona["ciudad"] = ???
persona["ciudad"] = "Pasto"

for clave, valor in persona.items():
    print(clave, ":", valor)

# Modifica la edad a 23
#persona
print("--------------------")
persona["edad"] = 23


# Elimina la clave "nombre"
# TODO
del persona["nombre"]

# Recorre el diccionario e imprime "clave: valor" por línea
# TODo
for clave, valor in persona.items():
    print(clave, ":", valor)

nombre : Luis
edad : 22
ciudad : Pasto
--------------------
edad : 23
ciudad : Pasto

### Mini–reto 1
Crea un diccionario `producto` con las claves: **"id"**, **"nombre"**, **"precio"** y **"stock"**.  
Luego:
1. Incrementa el `stock` en 5.
2. Cambia el `precio` (por ejemplo, descuéntalo un 10%).
3. Imprime cada par *clave: valor*.

In [ ]:
producto = {
    "id": 101,
    "nombre": "Memoria_Ram",
    "precio": 40000,
    "stock": 25
}

print(producto)
# Incrementa el stock en 5
producto["stock"] += 5

# Cambia el precio (por ejemplo, descuéntalo un 10%)
producto["precio"] *= 0.9

print("------------------------------")
for clave, valor in producto.items():
    print(clave, ":", valor)


# Imprime cada par clave: valor
# producto = {...}
# TODO

{'id': 101, 'nombre': 'Memoria_Ram', 'precio': 40000, 'stock': 25}
------------------------------
id : 101
nombre : Memoria_Ram
precio : 36000.0
stock : 30

## 2) De diccionarios a tablas con pandas (40 min)
**pandas** nos permite trabajar con datos como si fueran tablas de Excel.

### Ejemplo guiado

In [ ]:
import pandas as pd

datos = [
    {"nombre": "Ana", "edad": 20, "nota": 4.5},
    {"nombre": "Luis", "edad": 22, "nota": 3.8},
    {"nombre": "María", "edad": 21, "nota": 4.2},
]

df = pd.DataFrame(datos)
df

  nombre  edad  nota
0    Ana    20   4.5
1   Luis    22   3.8
2  María    21   4.2

### Operaciones básicas con `DataFrame`

In [ ]:
# Ver primeras filas
df.head()

  nombre  edad  nota
0    Ana    20   4.5
1   Luis    22   3.8
2  María    21   4.2

In [ ]:
# Seleccionar una columna
df["nombre"]

0      Ana
1     Luis
2    María
Name: nombre, dtype: object

In [ ]:
# Estadísticos rápidos
df.describe()

       edad      nota
count   3.0  3.000000
mean   21.0  4.166667
std     1.0  0.351188
min    20.0  3.800000
25%    20.5  4.000000
50%    21.0  4.200000
75%    21.5  4.350000
max    22.0  4.500000

### Mini–reto 2
1. Crea una lista de 4 diccionarios con `nombre`, `edad` y `nota`.
2. Conviértela a `DataFrame`.
3. Muestra solo la columna `nota`.
4. Calcula el **promedio** de `nota`.

In [ ]:
# Escribe tu solución aquí
# datos2 = [...]
# df2 = pd.DataFrame(datos2)
# df2["nota"]
# df2["nota"].mean()
# TODO

import pandas as pd

# Lista de diccionarios
estudiantes = [
    {"nombre": "Valeria", "edad": 20, "nota": 4.5},
    {"nombre": "Iván", "edad": 22, "nota": 3.8},
    {"nombre": "Nina", "edad": 21, "nota": 4.2},
    {"nombre": "Camila", "edad": 23, "nota": 4.9}
]

# Convertir a DataFrame
df = pd.DataFrame(estudiantes)
print("------------------------------")
print(df)
print("------------------------------")

# Mostrar solo la columna nota
print("Columna Notas")
print(df["nota"])

# Calcular promedio de nota
print("------------------------------")
promedio = df["nota"].mean()
print("\nPromedio de nota:", promedio)

------------------------------
    nombre  edad  nota
0  Valeria    20   4.5
1     Iván    22   3.8
2     Nina    21   4.2
3   Camila    23   4.9
------------------------------
Columna Notas
0    4.5
1    3.8
2    4.2
3    4.9
Name: nota, dtype: float64
------------------------------

Promedio de nota: 4.35

## 3) Ciclos: for y while (30 min)
Sirven para **repetir** acciones.

In [ ]:
# for con range
for i in range(3):
    print("Repetición", i)

Repetición 0
Repetición 1
Repetición 2

In [ ]:
# while con contador
contador = 0
while contador < 3:
    print("Contador:", contador)
    contador += 1

Contador: 0
Contador: 1
Contador: 2

### Mini–reto 3
Usando un `for`, recorre el `DataFrame df` y imprime el texto:  
`"Nombre: <nombre> - Nota: <nota>"` por cada fila.

In [ ]:
# Pista: puedes iterar sobre df.iterrows()
# for idx, fila in df.iterrows():
#     print("Nombre:", fila["nombre"], "- Nota:", fila["nota"])
# TODO

import pandas as pd

# DataFrame de ejemplo
nombres = [
    {"nombre": "Valeria", "edad": 20, "nota": 4.5},
    {"nombre": "Iván", "edad": 22, "nota": 3.8},
    {"nombre": "Nina", "edad": 21, "nota": 4.2},
    {"nombre": "Camila", "edad": 23, "nota": 4.9}
]

df = pd.DataFrame(nombres)

# Recorrer con for
for _, fila in df.iterrows():
    print(f"Nombre: {fila['nombre']} - Nota: {fila['nota']}")

Nombre: Valeria - Nota: 4.5
Nombre: Iván - Nota: 3.8
Nombre: Nina - Nota: 4.2
Nombre: Camila - Nota: 4.9

## 4) Funciones (30 min)
Una función encapsula lógica para **reutilizar** código.

In [ ]:
# Ejemplo simple
def saludar(nombre):
    print(f"Hola {nombre}, ¡bienvenido!")

# Prueba
saludar("Valeria Valentina")

Hola Valeria Valentina, ¡bienvenido!

### Mini–reto 4
Crea una función `filtrar_aprobados(df, umbral=4.0)` que reciba un DataFrame y retorne solo las filas con `nota >= umbral`.

In [ ]:
# Escribe tu función aquí
# def filtrar_aprobados(df, umbral=4.0):
#     ...
# return df_filtrado
# TODO

# Prueba con df
# filtrar_aprobados(df)
# TODO

import pandas as pd

def filtrar_aprobados(df, umbral=4.0):
    return df[df["nota"] >= umbral]

# Ejemplo de uso
lista = [
    {"nombre": "Ana", "edad": 20, "nota": 4.5},
    {"nombre": "Luis", "edad": 22, "nota": 3.8},
    {"nombre": "Carlos", "edad": 22, "nota": 3.2},
    {"nombre": "Mario", "edad": 22, "nota": 3.0},
    {"nombre": "Marta", "edad": 21, "nota": 4.2},
    {"nombre": "Juan", "edad": 23, "nota": 4.9}
]

df = pd.DataFrame(lista)

aprobados = filtrar_aprobados(df)
print(aprobados)

  nombre  edad  nota
0    Ana    20   4.5
4  Marta    21   4.2
5   Juan    23   4.9

## 5) 🧪 Laboratorio Final Integrador (35–40 min)

### Objetivo
Integrar **diccionarios + pandas + ciclos + funciones**.

### Instrucciones
1. Crea una **lista de 6 diccionarios** con `nombre`, `edad`, `nota` (decimal) y `ciudad`.
2. Conviértela a `DataFrame` (`df_lab`).
3. Recorre la tabla e imprime `"Nombre - Ciudad - Nota"`.
4. Crea una función `mejores(df, umbral)` que **retorne** un nuevo DataFrame con notas `>= umbral`.
5. Aplica `mejores(df_lab, 4.0)` y guarda el resultado en `top`.
6. Calcula el **promedio** de `nota` de `top` y muéstralo.
7. Exporta `top` a un archivo CSV llamado `mejores_estudiantes.csv`.

> Extra (opcional): añade una columna `estado` con el texto `"APROBADO"` si `nota >= 4.0`, en caso contrario `"EN PROCESO"`.

In [ ]:
# Escribe tu solución del laboratorio aquí
# Paso 1: datos = [ {...}, ... ]
# Paso 2: df_lab = pd.DataFrame(datos)
# Paso 3: recorrer con for / iterrows()
# Paso 4: def mejores(df, umbral): ...
# Paso 5: top = mejores(df_lab, 4.0)
# Paso 6: promedio_top = ...
# Paso 7: exportar CSV -> df.to_csv("mejores_estudiantes.csv", index=False)
# Extra: crear columna 'estado'
# TODO

import pandas as pd

# 1. Lista de 6 diccionarios
estudiantes = [
    {"nombre": "Ana",   "edad": 20, "nota": 4.5, "ciudad": "Pasto"},
    {"nombre": "Luis",  "edad": 22, "nota": 3.8, "ciudad": "Medellín"},
    {"nombre": "Marta", "edad": 21, "nota": 4.2, "ciudad": "Cali"},
    {"nombre": "Juan",  "edad": 23, "nota": 3.9, "ciudad": "Pereira"},
    {"nombre": "Sofia", "edad": 20, "nota": 3.5, "ciudad": "Bogotá"},
    {"nombre": "Pedro", "edad": 24, "nota": 4.0, "ciudad": "Manizales"}
]

# 2. Convertir a DataFrame
df_lab = pd.DataFrame(estudiantes)

# 3. Recorrer la tabla e imprimir "Nombre - Ciudad - Nota"
print("Nombres, Ciudades, Notas:")
for _, fila in df_lab.iterrows():
    print(f"{fila['nombre']} - {fila['ciudad']} - {fila['nota']}")

# 4. Función mejores(df, umbral)
def func_mejores(df, umbral):
    return df[df["nota"] >= umbral]

# 5. Filtrar con umbral = 4.0
print("\n--------------------------------------------")
top = func_mejores(df_lab, 4.0)
print("Type Top= ",type(top))

# 6. Calcular promedio de nota de top
print("\n--------------------------------------------")
promedio_grl = df_lab["nota"].mean()
print("Promedio de nota (general):", promedio_grl)

promedio_top = top["nota"].mean()
print("Promedio de nota (top):", promedio_top)

# 7. Exportar top a CSV
top.to_csv("mejores_estudiantes.csv", index=False)

# Extra: añadir columna estado
df_lab["estado"] = df_lab["nota"].apply(lambda x: "APROBADO" if x >= 4.0 else "EN PROCESO")
print("\nDataFrame con estado:\n", df_lab)

Nombres, Ciudades, Notas:
Ana - Pasto - 4.5
Luis - Medellín - 3.8
Marta - Cali - 4.2
Juan - Pereira - 3.9
Sofia - Bogotá - 3.5
Pedro - Manizales - 4.0

--------------------------------------------
Type Top=  <class 'pandas.core.frame.DataFrame'>

--------------------------------------------
Promedio de nota (general): 3.9333333333333336
Promedio de nota (top): 4.233333333333333

DataFrame con estado:
   nombre  edad  nota     ciudad      estado
0    Ana    20   4.5      Pasto    APROBADO
1   Luis    22   3.8   Medellín  EN PROCESO
2  Marta    21   4.2       Cali    APROBADO
3   Juan    23   3.9    Pereira  EN PROCESO
4  Sofia    20   3.5     Bogotá  EN PROCESO
5  Pedro    24   4.0  Manizales    APROBADO